# Generated by Django 5.2.7 on 2025-11-20 02:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('tipos_muestras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('examen_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(help_text='Código corto o mnemotécnico (Ej: GLU, HMG)', max_length=20, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categorias.categoriaexamen', verbose_name='Categoría')),
                ('tipo_muestra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipos_muestras.tipomuestra', verbose_name='Tipo de Muestra Requerido')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'db_table': 'Examenes',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetodoExamen',
            fields=[
                ('metodo_examen_id', models.AutoField(primary_key=True, serialize=False)),
                ('metodo', models.CharField(help_text='Ej: Espectrofotometría, Inmunoensayo', max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos', to='examenes.examen')),
            ],
            options={
                'verbose_name': 'Método del Examen',
                'verbose_name_plural': 'Métodos del Examen',
                'db_table': 'Examenes_Metodos',
            },
        ),
        migrations.CreateModel(
            name='ValorReferencia',
            fields=[
                ('valor_referencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(choices=[('Indistinto', 'Ambos Sexos'), ('M', 'Masculino'), ('F', 'Femenino')], default='Indistinto', max_length=10, verbose_name='Sexo')),
                ('edad_minima', models.PositiveIntegerField(default=0, verbose_name='Edad Mín (Años)')),
                ('edad_maxima', models.PositiveIntegerField(default=120, verbose_name='Edad Máx (Años)')),
                ('rango_referencia', models.CharField(max_length=100, verbose_name='Rango o Valor')),
                ('unidad_medida', models.CharField(blank=True, max_length=50, verbose_name='Unidad')),
                ('tipo_resultado', models.CharField(choices=[('Cuantitativo', 'Cuantitativo (Número)'), ('Cualitativo', 'Cualitativo (Texto)')], default='Cuantitativo', max_length=20)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_referencia', to='examenes.examen')),
            ],
            options={
                'verbose_name': 'Valor de Referencia',
                'verbose_name_plural': 'Valores de Referencia',
                'db_table': 'Examenes_Valores_Referencia',
            },
        ),
    ]
