# Generated by Django 5.2.7 on 2025-11-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodoexamen',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='valorreferencia',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='valorreferencia',
            name='unidad_medida',
            field=models.CharField(blank=True, help_text='Ej: mg/dL (Dejar en blanco si no aplica)', max_length=50, verbose_name='Unidad de Medida'),
        ),
    ]
