# Generated by Django 5.2.7 on 2025-11-06 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convenios', '0001_initial'),
        ('examenes', '0002_metodoexamen_estado_valorreferencia_estado_and_more'),
        ('pacientes', '0001_initial'),
        ('paquetes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('orden_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('Rutina', 'Rutina'), ('Preferente', 'Preferente'), ('Urgente', 'Urgente')], default='Rutina', max_length=20)),
                ('metodo_entrega', models.CharField(choices=[('Correo', 'Correo'), ('WhatsApp', 'WhatsApp'), ('Impreso', 'Impreso'), ('Teléfono', 'Teléfono')], default='Impreso', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='convenios.convenio', verbose_name='Convenio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'db_table': 'Ordenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_en_orden', models.DecimalField(decimal_places=2, max_digits=8)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examenes.examen')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden')),
            ],
            options={
                'db_table': 'Ordenes_Examenes',
                'unique_together': {('orden', 'examen')},
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='examenes',
            field=models.ManyToManyField(blank=True, related_name='ordenes', through='ordenes.OrdenExamen', to='examenes.examen'),
        ),
        migrations.CreateModel(
            name='OrdenPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_en_orden', models.DecimalField(decimal_places=2, max_digits=8)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paquetes.paquete')),
            ],
            options={
                'db_table': 'Ordenes_Paquetes',
                'unique_together': {('orden', 'paquete')},
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='paquetes',
            field=models.ManyToManyField(blank=True, related_name='ordenes', through='ordenes.OrdenPaquete', to='paquetes.paquete'),
        ),
    ]
