# Generated by Django 5.2.7 on 2025-11-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMuestra',
            fields=[
                ('tipo_muestra_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('condiciones_almacenamiento', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Muestra',
                'verbose_name_plural': 'Tipos de Muestras',
                'db_table': 'Tipos_Muestras',
                'ordering': ['tipo_muestra_id'],
            },
        ),
    ]
