# Generated by Django 5.2.7 on 2025-11-20 02:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('muestra_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(blank=True, help_text='Código único de la etiqueta de la muestra', max_length=50, null=True, unique=True)),
                ('fecha_toma', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('Recepcionada', 'Recepcionada'), ('En Análisis', 'En Análisis'), ('Validación', 'En Validación'), ('Finalizado', 'Finalizado'), ('Rechazada', 'Rechazada')], default='Recepcionada', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Ej: Muestra hemolizada, cantidad insuficiente...')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras_registradas', to='ordenes.orden')),
            ],
            options={
                'verbose_name': 'Muestra de Paciente',
                'verbose_name_plural': 'Muestras de Pacientes',
                'db_table': 'Muestras',
                'ordering': ['-fecha_toma'],
            },
        ),
    ]
