# Generated by Django 5.2.7 on 2025-11-20 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muestras', '0001_initial'),
        ('tipos_muestras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='responsable_toma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsable de la Toma'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='tipo_muestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipos_muestras.tipomuestra', verbose_name='Tipo de Muestra'),
        ),
    ]
