# Generated by Django 5.2.7 on 2025-11-05 17:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examenes', '0002_metodoexamen_estado_valorreferencia_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('paquete_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
                'db_table': 'Paquetes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteExamen',
            fields=[
                ('paquete_examen_id', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el paquete')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', help_text='Estado de este examen dentro del paquete', max_length=20)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.examen')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.paquete')),
            ],
            options={
                'verbose_name': 'Examen en Paquete',
                'verbose_name_plural': 'Exámenes en Paquetes',
                'db_table': 'Paquetes_Examenes',
                'ordering': ['paquete', 'orden'],
                'unique_together': {('paquete', 'examen')},
            },
        ),
        migrations.AddField(
            model_name='paquete',
            name='examenes',
            field=models.ManyToManyField(related_name='paquetes', through='paquetes.PaqueteExamen', to='examenes.examen'),
        ),
    ]
