# Generated by Django 5.2.7 on 2025-10-22 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paciente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('dui', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El DUI debe tener el formato 12345678-9.', regex='^\\d{8}-\\d{1}$')])),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
