# Generated by Django 5.2.7 on 2025-11-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paciente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('dui', models.CharField(max_length=10, unique=True)),
                ('telefono', models.CharField(max_length=8)),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('edad_al_registro', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad al Registro')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'Pacientes',
                'ordering': ['paciente_id'],
            },
        ),
    ]
