# Generated by Django 5.2.7 on 2025-11-20 02:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('factura_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_dui', models.CharField(blank=True, max_length=10)),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Pago'), ('Pagada', 'Pagada'), ('Parcial', 'Pago Parcial'), ('Anulada', 'Anulada')], default='Pendiente', max_length=20)),
                ('tipo_factura', models.CharField(choices=[('Particular', 'Factura Particular'), ('Convenio', 'Crédito Fiscal (Convenio)')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
