# Generated by Django 5.2.7 on 2025-11-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('convenio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre oficial de la entidad', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('Clínica', 'Clínica'), ('Hospital', 'Hospital'), ('Empresa', 'Empresa'), ('Doctor', 'Doctor')], max_length=20)),
                ('persona_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('correo_contacto', models.EmailField(max_length=100)),
                ('tipo_facturacion', models.CharField(choices=[('Convenio', 'Facturar al Convenio'), ('Paciente', 'Facturar al Paciente')], default='Paciente', help_text='Indica a quién se le emitirá la factura por defecto.', max_length=20)),
                ('condiciones_pago', models.TextField(help_text='Detalles del acuerdo de pago')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
                'db_table': 'Convenios',
                'ordering': ['nombre'],
            },
        ),
    ]
