<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-22 00:33

=======
# Generated by Django 5.2.7 on 2025-10-22 23:00

import django.db.models.deletion
>>>>>>> backup-local
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('examenes', '0001_initial'),
>>>>>>> backup-local
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('convenio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre oficial de la entidad', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('Clínica', 'Clínica'), ('Hospital', 'Hospital'), ('Empresa', 'Empresa'), ('Doctor', 'Doctor')], max_length=20)),
<<<<<<< HEAD
                ('contacto', models.CharField(help_text='Nombre de la persona de contacto', max_length=100)),
=======
                ('persona_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('correo_contacto', models.EmailField(max_length=100)),
                ('tipo_facturacion', models.CharField(choices=[('Convenio', 'Facturar al Convenio'), ('Paciente', 'Facturar al Paciente')], default='Paciente', help_text='Indica a quién se le emitirá la factura por defecto.', max_length=20)),
                ('descuento_general', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento general (ej: 10.5 para 10.5%). Se aplica si no hay un descuento específico.', max_digits=5)),
>>>>>>> backup-local
                ('condiciones_pago', models.TextField(help_text='Detalles del acuerdo de pago')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
                'ordering': ['nombre'],
            },
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='DescuentoEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento SOLO para este examen (ej: 25.0).', max_digits=5)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos_especificos', to='convenios.convenio')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios_con_descuento', to='examenes.examen')),
            ],
            options={
                'verbose_name': 'Descuento Específico',
                'verbose_name_plural': 'Descuentos Específicos',
                'unique_together': {('convenio', 'examen')},
            },
        ),
>>>>>>> backup-local
    ]
