# Generated by Django 5.2.7 on 2025-11-20 02:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examenes', '0001_initial'),
        ('paquetes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('convenio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre oficial de la entidad', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('Clínica', 'Clínica'), ('Hospital', 'Hospital'), ('Empresa', 'Empresa'), ('Doctor', 'Doctor'), ('Seguro', 'Aseguradora')], max_length=20)),
                ('persona_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('correo_contacto', models.EmailField(max_length=100)),
                ('tipo_facturacion', models.CharField(choices=[('Convenio', 'Facturar al Convenio'), ('Paciente', 'Facturar al Paciente')], default='Paciente', help_text='A quién se le emite la factura.', max_length=20)),
                ('condiciones_pago', models.TextField(help_text='Ej: Crédito 30 días, Contra entrega')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('descuento_general_examenes', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desc. General Exámenes (%)')),
                ('descuento_general_paquetes', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desc. General Paquetes (%)')),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
                'db_table': 'Convenios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConvenioExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos_examenes', to='convenios.convenio')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.examen')),
            ],
            options={
                'db_table': 'Convenios_Examenes',
                'unique_together': {('convenio', 'examen')},
            },
        ),
        migrations.CreateModel(
            name='ConvenioPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos_paquetes', to='convenios.convenio')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.paquete')),
            ],
            options={
                'db_table': 'Convenios_Paquetes',
                'unique_together': {('convenio', 'paquete')},
            },
        ),
    ]
