<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-22 00:33
=======
# Generated by Django 5.2.7 on 2025-10-22 23:00
>>>>>>> backup-local

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
>>>>>>> backup-local
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
    ]
