# Generated by Django 5.2.7 on 2025-11-20 02:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoDetalle',
            fields=[
                ('resultado_detalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_obtenido', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Resultado (Detalle)',
                'verbose_name_plural': 'Resultados (Detalles)',
                'db_table': 'Resultados_Detalle',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('resultado_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Pendiente', 'Ingreso de Datos'), ('En Espera', 'En Espera de Validación'), ('Validado', 'Validado Final')], default='Pendiente', max_length=20)),
                ('observaciones_generales', models.TextField(blank=True, help_text='Observaciones generales del informe (ej: Muestra lipémica)', null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='ordenes.orden')),
            ],
            options={
                'verbose_name': 'Resultado (Encabezado)',
                'verbose_name_plural': 'Resultados (Encabezados)',
                'db_table': 'Resultados',
            },
        ),
    ]
