# Generated by Django 5.2.7 on 2025-11-20 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examenes', '0001_initial'),
        ('resultados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultadodetalle',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='resultados.resultado'),
        ),
        migrations.AddField(
            model_name='resultadodetalle',
            name='valor_referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_obtenidos', to='examenes.valorreferencia'),
        ),
        migrations.AlterUniqueTogether(
            name='resultadodetalle',
            unique_together={('resultado', 'valor_referencia')},
        ),
    ]
